spring:
  zipkin:
    base-url: http://47.100.108.108:9411/
    sleuth:
      sampler:
        probability: 1 #样本采集量，默认为0.1，为了测试这里修改为1，正式环境一般使用默认值。
    sender:
      type: web
management:
  endpoint:
    health:
      show-details: always
feign:
  hystrix:
    enabled: true
# 设置服务调用时间为2秒
ribbon:
  ReadTimeout: 2000
  ConnectionTimeout: 2000
  http:
    client:
      enabled: true
logging:
  path: /home/zlm-app-emp-logs
  config: classpath:logback-dev.xml
env:
  test
