spring:
#   profiles:
#     active: dev
#   application:
#     name: zlm-app-partner
#   cloud:
#     client:
#       ipAddress: 127.0.0.1 #本地
# #        ipAddress: 10.102.24.128 #测试
#   #      ipAddress: 119.3.19.168 #线上
  zipkin:
#    base-url: http://10.102.24.128:9411/
    base-url: http://47.100.108.108:9411/
    sleuth:
      sampler:
        probability: 1#样本采集量，默认为0.1，为了测试这里修改为1，正式环境一般使用默认值。
    sender:
      type: web
# eureka:
#   client:
#     serviceUrl: #注册中心的注册地址
#       defaultZone: http://127.0.0.1:6901/eureka/
# #        defaultZone: http://10.102.24.128:6901/eureka/  #测试
#   #      defaultZone: http://119.3.19.168:6901/eureka/   #线上
#   instance:
#     prefer-ip-address: true
#     instance-id: ${spring.cloud.client.ipAddress}:${server.port}
management:
  endpoint:
    health:
      show-details: always
feign:
  hystrix:
    enabled: true
# 设置服务调用时间为2秒
ribbon:
  ReadTimeout: 2000
  ConnectionTimeout: 2000
  http:
    client:
      enabled: true
logging:
  path: /home/zlm-app-partner-logs
  config: classpath:logback-dev.xml
